version: 1
services:
  - type: web
    name: kasu
    env: docker
    plan: free
    buildCommand: yarn
    startCommand: yarn start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 16
