version: 1
services:
  - type: web
    name: わかめtube
    env: docker
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 16
